name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      host: 3.122.72.29
      user: bitnami
      port: 22
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCU1eRBaqt976LE15Cjg/dlQ92d3SzroY6ZBkj3zDtl92Df1M6AVWciCA2BookZ8qmlAwYEXftai5EXeQ2yjzNMoiTKxF4bLNG7JSedEVUW69vJK86FMQBFFh8YeeHrLWXRnBr1+iwjeTazzdgd4X0eEFJyiY5crXPJPg9Tbsn/TDfMTff8m32HE8yD1ZhLljwEh4Yw6VvzhfvCHhQNb6Xd55GsRIYgmctEE0yOU6/0IBj/jy3q7fTrr7xFjlx/UzpbuP/HmstLL+KAx/uiAGnRWbAaBmnACsTb/GG0z1MUr/H87v7C94VrAMnq4DBMTCeBnHd1LF1wvwimD7YSvggf imported-openssh-key


    steps:
    - uses: actions/checkout@v3

   
    - name : APT UPDATE
      run:
        sudo apt update && sudo apt install sshpass
    
    - name: cd repertoir
      run:
        sshpass -e ssh -o stricthostkeychecking=yes  ${{ env.host }}@${{ env.user }}@${{ env.port }}@${{ env.key }}

    
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
