name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      host: 3.122.72.29
      user: bitnami
      port: 22
      key: /home/bitnami/.ssh/id_rsa


    steps:
    - uses: actions/checkout@v3

   
    - name : APT UPDATE
      run:
        sudo apt update && sudo apt install sshpass
    
    - name: cd repertoir
      run:
        sshpass -e ssh -o stricthostkeychecking=no ${{ env.key }}@${{ env.host }}@${{ env.user }}@${{ env.port }}

    
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
