name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APP_HOST: 3.122.72.29


    steps:
    - uses: actions/checkout@v3

   
    - name : APT UPDATE
      run:
        sudo apt update && sudo apt install sshpass
    
    - name: cd repertoir
      run:
       cd /home
       echo $APP_HOST
        #sshpass -e ssh -o stricthostkeychecking=no {{ APP_HOST }}@${{ secrets.APP_USER }}

    
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
