name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

   
    - name : APT UPDATE
      run:
        sudo apt update && sudo apt install sshpass

    - name: ssh key passphrase
      uses: ./
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.APP_USER }}
        key: ${{ secrets.APP_KEY }}
        port: ${{ secrets.APP_PORT }}
        script: |
          whoami
          ls -al

    #- name: my server
     # run:
      #  sshpass -e ssh -o stricthostkeychecking=no {{ secrets.APP_HOST }}@${{ secrets.APP_USER }}@${{ secrets.APP_USER }}
        #echo ${{ secrets.APP_USER }}
        #sshpass -e ssh -o stricthostkeychecking=no {{ secrets.APP_HOST }}@${{ secrets.APP_USER }}

    
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
