name: CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      APP_USER: bitnami

    steps:
      - uses: actions/checkout@v2
      
      - name: APT UPDATE and INSTALL SSHPASS
        run: 
          sudo apt update && sudo apt install sshpass
          
      - name: deploy
        run: 
          sshpass -e ssh -o stricthostkeychecking=no ${{ APP_USER }}@${{ APP_HOST }}@${{ APP_KEY }}@${{ APP_PORT }}
